### ISSUE TITLE
Generate throws error, emu.device undefined

### ISSUE THREAD

**Issue by skypanther** [skypanther/simplesim#10]
``` shell
≫ simplesim generate --no-prefix

/usr/local/lib/node_modules/simplesim/index.js:223
        found = emu.device.match(/s\d\s|Galaxy\sNexus|Nexus(\s{1}\w*)*|Motorola(\s{1
                           ^
TypeError: Cannot call method 'match' of undefined
    at makeAlias (/usr/local/lib/node_modules/simplesim/index.js:223:22)
    at /usr/local/lib/node_modules/simplesim/index.js:84:14
```

**Comment by skypanther** [comment]
Resolved by version 0.1.1
